const sampleData = {
  products: [
    {
      name: 'Black grape',
      slug: 'black-grape',
      category: 'Liquids',
      description: '|A taste of black grape taste',
      images: ['/images/sample-products/black-grape.png'],
      price: 4.99,
      brand: 'Whoop',
      rating: 4.5,
      numReviews: 10,
      stock: 5,
      isFeatured: true,
      banner: 'banner-1.jpg',
    },
    {
      name: 'Strawberry Kiwi',
      slug: 'strawberry-kiwi',
      category: 'Liquids',
      description: 'A taste of strawberry and kiwiw',
      images: ['/images/sample-products/strawberry-kiwi.png'],
      price: 4.99,
      brand: 'Whoop',
      rating: 4.2,
      numReviews: 8,
      stock: 10,
      isFeatured: true,
      banner: 'banner-2.jpg',
    },
    {
      name: 'Apple',
      slug: 'apple',
      category: 'Liquids',
      description: 'A taste of apple',
      images: ['/images/sample-products/apple.png'],
      price: 4.99,
      brand: 'Whoop',
      rating: 4.9,
      numReviews: 3,
      stock: 0,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Banana',
      slug: 'banana',
      category: 'Liquids',
      description: 'A taste of banana',
      images: ['/images/sample-products/banana.png'],
      price: 4.99,
      brand: 'Whoop',
      rating: 3.6,
      numReviews: 5,
      stock: 10,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Berries',
      slug: 'berries',
      category: 'Liquids',
      description: 'A taste of berries',
      images: ['/images/sample-products/berries.png'],
      price: 4.99,
      brand: 'Whoop',
      rating: 4.7,
      numReviews: 18,
      stock: 6,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Watermelon',
      slug: 'watermelon',
      category: 'Liquids',
      description: 'A taste of watermelon',
      images: ['/images/sample-products/watermelon.png'],
      price: 4.99,
      brand: 'Whoop',
      rating: 4.6,
      numReviews: 12,
      stock: 8,
      isFeatured: true,
      banner: null,
    },
  ],
};

export default sampleData;
